# typed: false
# frozen_string_literal: true

# Generated by scripts/update-formula.sh from the published checksums.
# Do not edit by hand -- the next run overwrites it.
class Gravv < Formula
  desc "CLI/TUI tool for the Gravv financial payments platform"
  homepage "https://github.com/GravityFinance/gravv-cli-releases"
  version "0.1.9"
  license "MIT"

  on_macos do
    on_intel do
      url "https://gravv-cli.s3.us-east-1.amazonaws.com/releases/v0.1.9/gravv_0.1.9_darwin_amd64.tar.gz"
      sha256 "05b477f5dbaa67d44dc32a540423194bbd64d58da5198aa2be11da9fe6abd425"
    end
    on_arm do
      url "https://gravv-cli.s3.us-east-1.amazonaws.com/releases/v0.1.9/gravv_0.1.9_darwin_arm64.tar.gz"
      sha256 "527f6f2769160db5de0cd40a712bb908be5ef5d6d82f7f7d4e037f360bf4ea8c"
    end
  end

  on_linux do
    on_intel do
      url "https://gravv-cli.s3.us-east-1.amazonaws.com/releases/v0.1.9/gravv_0.1.9_linux_amd64.tar.gz"
      sha256 "8d158c075a31771bc4dfe8ca8ba335bf06b9e291f5718aa26fdd07fbf1cb5ac3"
    end
    on_arm do
      url "https://gravv-cli.s3.us-east-1.amazonaws.com/releases/v0.1.9/gravv_0.1.9_linux_arm64.tar.gz"
      sha256 "de6a484f977dc2506f203a9f4b0a915c0a39260e78a0e7e80837730e115135f3"
    end
  end

  def install
    bin.install "gravv"
    generate_completions_from_executable(bin/"gravv", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gravv version")
  end
end
