# typed: false
# frozen_string_literal: true

# This formula is auto-generated by GoReleaser. Do not edit manually.
# To update, create a new release in gravv-cli repository.
class Gravv < Formula
  desc "CLI/TUI tool for the Gravv financial payments platform"
  homepage "https://github.com/GravityFinance/gravv-cli"
  version "0.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/GravityFinance/gravv-cli-releases/releases/download/v#{version}/gravv_#{version}_darwin_amd64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_DARWIN_AMD64"
    end
    on_arm do
      url "https://github.com/GravityFinance/gravv-cli-releases/releases/download/v#{version}/gravv_#{version}_darwin_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_DARWIN_ARM64"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/GravityFinance/gravv-cli-releases/releases/download/v#{version}/gravv_#{version}_linux_amd64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_LINUX_AMD64"
    end
    on_arm do
      url "https://github.com/GravityFinance/gravv-cli-releases/releases/download/v#{version}/gravv_#{version}_linux_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_LINUX_ARM64"
    end
  end

  def install
    bin.install "gravv"
    
    # Install shell completions
    generate_completions_from_executable(bin/"gravv", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gravv version")
  end
end
