#!/usr/bin/env bash
#
# Regenerate Formula/gravv.rb from the checksums published alongside a release.
#
#   scripts/update-formula.sh            # track whatever is current
#   scripts/update-formula.sh 0.2.0      # pin a version
#
# The formula is always regenerated from the published checksums.txt rather
# than edited in place, so a hand-edited or mis-typed hash is corrected on the
# next run instead of sticking around until the version happens to change.
#
set -euo pipefail

BASE_URL="${GRAVV_BASE_URL:-https://gravv-cli.s3.us-east-1.amazonaws.com}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FORMULA="$REPO_ROOT/Formula/gravv.rb"

version="${1:-}"
if [ -z "$version" ]; then
    version="$(curl -fsSL "$BASE_URL/releases/latest/version.txt" | tr -d '[:space:]')"
fi
version="${version#v}"

if [ -z "$version" ]; then
    echo "could not determine a version to publish" >&2
    exit 1
fi

checksums="$(curl -fsSL "$BASE_URL/releases/v${version}/checksums.txt")"

# sha_for <artifact-suffix> -- the checksum for one platform's tarball.
sha_for() {
    local suffix="$1" name sha
    name="gravv_${version}_${suffix}.tar.gz"
    sha="$(printf '%s\n' "$checksums" | awk -v n="$name" '$2 == n || $2 == "*" n {print $1}' | head -n 1)"
    if [ -z "$sha" ]; then
        echo "no checksum published for $name" >&2
        exit 1
    fi
    printf '%s' "$sha"
}

darwin_amd64="$(sha_for darwin_amd64)"
darwin_arm64="$(sha_for darwin_arm64)"
linux_amd64="$(sha_for linux_amd64)"
linux_arm64="$(sha_for linux_arm64)"

mkdir -p "$(dirname "$FORMULA")"
cat > "$FORMULA" <<FORMULA_EOF
# typed: false
# frozen_string_literal: true

# Generated by scripts/update-formula.sh from the published checksums.
# Do not edit by hand -- the next run overwrites it.
class Gravv < Formula
  desc "CLI/TUI tool for the Gravv financial payments platform"
  homepage "https://github.com/GravityFinance/gravv-cli-releases"
  version "${version}"
  license "MIT"

  on_macos do
    on_intel do
      url "${BASE_URL}/releases/v${version}/gravv_${version}_darwin_amd64.tar.gz"
      sha256 "${darwin_amd64}"
    end
    on_arm do
      url "${BASE_URL}/releases/v${version}/gravv_${version}_darwin_arm64.tar.gz"
      sha256 "${darwin_arm64}"
    end
  end

  on_linux do
    on_intel do
      url "${BASE_URL}/releases/v${version}/gravv_${version}_linux_amd64.tar.gz"
      sha256 "${linux_amd64}"
    end
    on_arm do
      url "${BASE_URL}/releases/v${version}/gravv_${version}_linux_arm64.tar.gz"
      sha256 "${linux_arm64}"
    end
  end

  def install
    bin.install "gravv"
    generate_completions_from_executable(bin/"gravv", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gravv version")
  end
end
FORMULA_EOF

echo "Formula regenerated for v${version}"
